# Change these first
owner: eaglercraftx1-8 # Your GitHub organization or username, where this repository lives
repo: eaglercraft-uptime # The name of this repository

sites:
  - name: EaglercraftX Site Links
    url: https://www.eaglercraft.win
  - name: Play (Netlify)
    url: https://play.eaglercraft.win
  - name: Fastest (Netlify)
    url: https://fastest.eaglercraft.win
  - name: Not Proxied Client (OnRender)
    url: https://notproxiedclient.eaglercraft.win
  - name: Client (Github Pages)
    url: https://client.eaglercraft.win
  - name: Client2 (OnRender)
    url: https://client2.eaglercraft.win
  - name: Client3 (Netlify)
    url: https://client3.eaglercraft.win

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
