# Change these first
owner: eaglercraftx1-8 # Your GitHub organization or username, where this repository lives
repo: eaglercraft-uptime # The name of this repository

sites:
  - name: EaglercraftX Site Links
    url: https://www.eaglercraft.win
  - name: Play (Netlify)
    url: https://play.eaglercraft.win
  - name: Fastest (Netlify)
    url: https://fastest.eaglercraft.win
  - name: Not Proxied Client (OnRender)
    url: https://notproxiedclient.eaglercraft.win
  - name: Client (Github Pages)
    url: https://client.eaglercraft.win
  - name: Client2 (OnRender)
    url: https://client2.eaglercraft.win
  - name: Client3 (Netlify)
    url: https://client3.eaglercraft.win

assignees:
  - PrestonT500

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /eaglercraft-uptime
  logoUrl: https://git.eaglercraft.win/EaglercraftX-Client-Collections/EaglercraftX-Site/raw/branch/main/images/eaglercommunity.png
  name: EagX Uptime Monitor
  introTitle: "**EaglercraftX Client Collections Site**"
  introMessage: Uptime Monitor
  navbar:
    - title: Our Site
      href: https://www.eaglercraft.win
    - title: Status
      href: /
    - title: Discord
      href: https://discord.eaglercraft.win
    - title: Gitea
      href: https://git.eaglercraft.win

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
